development:
  host: '127.0.0.1'
  port: 9042
  keyspace: blog_development

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: blog_test

production:
  hosts:
    - 'cass1.blog.biz'
    - 'cass2.blog.biz'
    - 'cass3.blog.biz'
  port: 9042
  keyspace: blog_production
  username: 'myappuser'
  password: 'password1'
